language: bash
branchs:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_e543db4018b8_key -iv $encrypted_e543db4018b8_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
after_success:
- chmod 0600 ~/.ssh/id_rsa
- ssh travis@123.56.22.140 -o StrictHostKeyChecking=no 'cd ~/blog/content/post &&
  git pull && cd ~/blog && hugo && rm -rf /usr/share/nginx/html/output/* && mv ~/blog/public/*
  /usr/share/nginx/html/output/'
